dbca -silent -createDatabase \
 -templateName General_Purpose.dbc \
 -gdbname NEXUSCDB \
 -sid NEXUSCDB \
 -createAsContainerDatabase true \
 -numberOfPDBs 0 \
 -databaseConfigType SI \
 -memoryMgmtType auto_sga \
 -totalMemory 4096 \
 -storageType FS \
 -datafileDestination /u01/app/oracle/oradata \
 -recoveryAreaDestination /u01/app/oracle/fast_recovery_area \
 -recoveryAreaSize 10240 \
 -emConfiguration NONE \
 -sampleSchema false \
 -sysPassword Oracle_123 \
 -systemPassword Oracle_123 \
 -characterSet AL32UTF8 \
 -nationalCharacterSet AL16UTF16
